services:
  - type: web
    name: transcript-server
    env: python
    buildCommand: pip install -r requirements.txt
    # Update this line to use the correct module name
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_API_KEY
        sync: false
